### ISSUE TITLE
Unable to deploy argocd to localdev cluster

### ISSUE THREAD

**Issue by zukwung** [second-front/gwctl#6]
When reading the logs of the fluxcd helm-controller, it seems like there is an error passing secrets to argo. not sure of the values are being passed so I can't pinpoint the error... 

```
{"level":"error","ts":"2025-04-03T14:30:25.016Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"argocd","namespace":"bigbang"},"namespace":"bigbang","name":"argocd","reconcileID":"681be6f1-e54a-47b8-85a9-922fc9049f8d","error":"template: argocd/templates/argocd-configs/argocd-secret.yaml:49:67: executing \"argocd/templates/argocd-configs/argocd-secret.yaml\" at <b64enc>: wrong type for value; expected string; got float64"}
```

I tried modifying the fake client secret from `123456789` to `123456789z` in case it was rendering as a number but no dice. any suggestions on how to proceed?

**Comment by itpick** [comment]
We have a fix coming.

Basically your password within the values file needs to change from "123456789" to "123456789a" with the additional "a" character for localdev.

You will need to update keycloak's values as well.  Or just wait for the fixed version.  Keycloak also needs the namespace created beforehand for the kustomization to work.

**Comment by itpick** [comment]
as workaround to create keycloak namespace you could apply this:
```
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  annotations:
    meta.helm.sh/release-name: bigbang
    meta.helm.sh/release-namespace: bigbang
  labels:
    app.kubernetes.io/managed-by: Helm
```
