### ISSUE TITLE
AuthService in CrashLoopBackOff because of APP configuration

### ISSUE THREAD

**Issue by zukwung** [second-front/gwctl#8]
I'm seeing authservice crashing with this error message: 

```sh
time="2025/04/11 20:26:57" level=error msg="unexpected exit" scope="default" error="1 errors occured:
invalid OIDC override from chain[APP].filter[0]: must not be root path: invalid callback URL"
Unexpected exit: 1 errors occured:
invalid OIDC override from chain[APP].filter[0]: must not be root path: invalid callback URL
```

I saw that its currently configured as such

```yaml
    chains:
      APP:
        callback_uri: https://APP.gw.local
        client_id: il2_eb21db65-3118-4017-bfe7-86829038d3dc_apps
        client_secret: 123456789z
        match:
          prefix: "APP.gw.local"
```

So i updated it to `https://APP.gw.local/oauth2/callback` based on [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/features/endpoints/), which I think is being used for our service in the 2f env and it deployed properly. 

So my question is, what is the correct value to put for the callback for the app, or is it more of a app-by-app type thing?
